# Site
repository: Laxchan/Laxchan.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lax Chan
title: RTT at the Università degli Studi del Piemonte Orientale 
email: lax.chan@uniupo.it


# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Laxchan


# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  
  I am currently a RTT of statistics at the Università degli Studi del Piemonte Orientale and an honorary assistant professor of statistics with the School of 
  Mathematics, University of Birmingham, United Kingdom. I previously worked at the University of Birmingham as an assitant professor of Statistics.
   
  My main research interests are in Functional data analysis (specifically in Small-ball probability, Single Functional Index Model). I am also interested in Multiple Systems estimation and its application. 
  
  If you are interested in a more detailed CV, please click below.
  
  [<mark>Download curriculum vitae</mark>](/files/CV_Lax.pdf)

# Projects Section
#projects_title: Academic Positions

# Experience Section
#experience_title: Industry Experience

# Education Section
#education_title: Education

# More Section
more_title: Publications
more_content: |

  **Articles in refereed journals**
  
  1. Silverman, B.W., **Chan, L.**, Vincent, K. (2024). Bootstrapping Multiple Systems Estimates to Account for Model Selection. *Statistics and Computing* **34**(44). 
  [[Link]](https://doi.org/10.1007/s11222-023-10346-9)
 
  1. Bongiorno, E. G., **Chan, L.**, Goia. A. (2023). Detecting the complexitiy of a Functional time series. *Journal of Nonparametric Statistics* 
  [[Link]](https://doi.org/10.1080/10485252.2023.2234507)
  
  1. **Chan, L.**, Delsol, L., Goia, A. (2023). A link function specification test in the Single Functional Index Model. *Advances in Data Analysis and Classification* 
  [[Link]](https://doi.org/10.1007/s11634-023-00545-7)
  
  1. **Chan, L.**, Silverman, B.W., Vincent, K. (2021). Multiple Systems Estimation for sparse capture data: inferential challenges when 
  there are non-overlapping lists. *Journal of American Statistical Association* **116**(535), 1297--1306. [[Link]](https://www.tandfonline.com/doi/full/10.1080/01621459.2019.1708748)
  [[R package]](https://cran.r-project.org/web/packages/SparseMSE/index.html)
  
  1. Dryden, I., Goulding, J. Preston, S., **Chan, L.** (2020). Discussion of Multiple-systems analysis for the quantification of modern slavery: 
  classical and Bayesian approaches by Silverman. *Journal of Royal Statistical Society: Series A* **183**(3), 691--736. [[Link]](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssa.12505)
  
  1. **Chan, L.**, Grimm, U., Short, I. (2018). Substitution-based structures with absolutely continuous spectrum. *Indagationes Mathematicae* **29**(4), 1072--1086.
  [[Link]](https://www.sciencedirect.com/science/article/pii/S0019357718302659)
  
  1. **Chan, L.**, Grimm. U. (2017). Spectrum of a Rudin–Shapiro-like sequence. *Advances in Applied Mathematics* **87**, 16--23.
  [[Link]](https://www.sciencedirect.com/science/article/pii/S0196885816301397) 
  
  1. **Chan, K.**, Nair. R. (2014). Problems in Strong Uniform Distribution. *Tatra Mountains Mathematical Publications* **59**, 51--64.
  [[Link]](https://sciendo.com/article/10.2478/tmmp-2014-0018)
  
  1. **Chan, K.**, Nair. R. (2014). A remark on the distribution of Chebyshev polynomials on [−1,1]. *Uniform distribution theory* **9**(2), 125--134
  [[Link]](https://pcwww.liv.ac.uk/~karpenk/JournalUDT/vol09/no2/08ChanNair.pdf)
  
  My registered name at the University of Liverpool was Kwo Chan, short for Kwo Lik Lax Chan.
  
  **Submitted papers** 

  
  **Conference proceedings and technical report**

  1. Bongiorno, E.G., **Chan, L.**, Goia, A. (2023) Nonparametric dimensionality detection for functional data *COMPSTAT 2023 Book of Abstracts*, ISBN 9789073592414
  [[Link]](http://www.compstat2023.org/BoA.php)

  1. **Chan, L.** (2023) On specifying a link function of a single functional index model. *COMPSTAT 2023 Book of Abstracts*, ISBN 9789073592414
  [[Link]](http://www.compstat2023.org/BoA.php)

  1. **Chan, L.**, Goia, A. (2023) Goodness--of--fit test for the single functional index model. *Cladag 2023 Book of short papers*, ISBN 978-88-9193-563-2 
  [[Link]](https://www.statlab-unisa.it/cladag2023/book-of-abstracts/)
  
  1. **Chan, L.** (2022) A specification test for the single functional index model. *CFE-CMStatistics 2022 Book of Abstracts*, ISBN 9789925781263
  [[Link]](http://www.cmstatistics.org/CMStatistics2022/BoA.php)
  
  1. Bongiorno, E.G., **Chan, L.**, Goia, A. (2021) Evaluating the complexity of a functional time series. *CFE-CMStatistics 2021 Book of Abstracts*, ISBN 9789925781256
  [[Link]](http://www.cmstatistics.org/CMStatistics2021/BoA.php)
  
  1. Bongiorno, E.G., **Chan, L.**, Goia, A., Vieu, P. (2021) About the complexity of a functional time series. *IWFOS 2021 Book of Abstracts*
  [[Link]](https://iwfos2021.sci.muni.cz/programme)
  
  1. Perez, I., **Chan, L.**, Torres, T. M., Goulding, J., Kypraios, T. (2018) On Bayesian inferential tasks with infinite-state jump processes: 
  efficient data augmentation. **Technical report** [[arXiv]](https://arxiv.org/abs/1806.02458)
  
  1. **Chan, L.**, Grimm, U. Substitution-based sequences with absolutely continuous diffraction, *Journal of Physics: Conference Series* **809**(012027)
  [[Link]](https://iopscience.iop.org/article/10.1088/1742-6596/809/1/012027)
  
  
# More Section
awards_title: Awards
awards_content: |
    **Academic awards**
    - Young scientist award to attend International conference on Quasicrystals Kathmandu, Nepal 2016
    - Partial funding to attend thematic month Oleron, France 2-16
    - Fully funded studentship with stipend 2014-2017
    - Liverpool affinity award 2013-2014
    - Faculty of physical sciences and engineering post graduate scholarship 2013-2014
    - University of Liverpool Departmental Scholarship for M.Sc. students 2013-2014
    - University of Liverpool Regional award 2010-2013
  

  
  





# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
 
