# Site
repository: Laxchan/Laxchan.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lax Chan
title: Junior assistant professor (RTD-A) at Università degli Studi del Piemonte Orientale 
email: lax.chan@uniupo.it


# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Laxchan


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a junior assistant professor (RTD-A) at the Università degli Studi del Piemonte Orientale under the mentorship of Prof. [Aldo Goia](https://upobook.uniupo.it/aldo.goia) and Prof. [Enea Bongiorno](https://upobook.uniupo.it/enea.bongiorno).
  
  My research interests are in Functional data analysis (Small-ball probability, Single Functional Index Model) and Multiple Systems estimation and its application to human rights.
  
  If you are interested in a more detailed CV, please click below.
  
  [<mark>Download curriculum vitae</mark>](/files/CV_Lax.pdf)
# Teaching Section
teaching_title: Teaching at UPO
teaching_content: |

 **Laurea Magistrale course**
    - Statistics for Finance 
    
# Projects Section
projects_title: Academic Positions

# Experience Section
#experience_title: Industry Experience

# Education Section
education_title: Education

# More Section
more_title: Publications
more_content: |

  **Articles in refereed journals**
  
  1. **Chan, L.**, Silverman, B.W., Vincent, K. (2021). Multiple Systems Estimation for sparse capture data: inferential challenges when 
  there are non-overlapping lists. *Journal of American Statistcal Association* **116**(535), 1297--1306. [[Link]](https://www.tandfonline.com/doi/full/10.1080/01621459.2019.1708748) 
  
  1. Dryden, I., Goulding, J. Preston, S., **Chan, L.** (2020). Discussion of Multiple-systems analysis for the quantification of modern slavery: 
  classical and Bayesian approaches by Silverman. *Journal of Royal Statistical Society: Series A* **183**(3), 691--736. [[Link]](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssa.12505)
  
  1. **Chan, L.**, Grimm, U., Short, I. (2018). Substitution-based structures with absolutely continuous spectrum. *Indagationes Mathematicae* **29**(4), 1072--1086.
  [[Link]](https://www.sciencedirect.com/science/article/pii/S0019357718302659)




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
 
