# Site
repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lax Chan
title: Junior assistant professor (RTD-A) at Università degli Studi del Piemonte Orientale 
email: lax.chan@uniupo.it


# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Laxchan


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a junior assistant professor (RTD-A) at the Università degli Studi del Piemonte Orientale under the mentorship of Prof. [Aldo Goia](https://upobook.uniupo.it/aldo.goia) and Prof. [Enea Bongiorno](https://upobook.uniupo.it/enea.bongiorno).
  
  My research interests are:
  
  - Functional data analysis (Small-ball probability, Single Functional Index Model)
  
  - Multiple Systems estimation and its application to human rights




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
