# Site
repository: Laxchan/Laxchan.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lax Chan
title: RTT at the Università degli Studi del Piemonte Orientale 
email: lax.chan@uniupo.it


# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Laxchan


# About Section
# about_title: About Me
about_profile_image: images/Lax-Chan.png
about_content: | # this will include new lines to allow paragraphs
  
  I am currently a RTT of statistics at the Università degli Studi del Piemonte Orientale, Italy and an honorary assistant professor of statistics with the School of 
  Mathematics, University of Birmingham, United Kingdom, where until May 2025, I worked as an assistant professor of Statistics.
   
  My main research interests are in Functional data analysis (specifically in Small-ball probability, Single Functional Index Model). I am also interested in Multiple Systems estimation and its application. 
  
  If you are interested in a more detailed CV, please click below.
  
  [<mark>Download curriculum vitae</mark>](/files/resume.pdf)



# More Section
more_title: Publications
more_content: |

  **Articles in refereed journals**

  1. Bongiorno, E. G., **Chan, L.**, Goia. A. (2025+). Decomposing Complexity Mixture Processes on Metric Spaces. *Accepted in Journal of Statistical Computation and Simulation* 
  
  1. Silverman, B.W., **Chan, L.**, Vincent, K. (2024). Bootstrapping Multiple Systems Estimates to Account for Model Selection. *Statistics and Computing* **34**(44). 
  [[Link]](https://doi.org/10.1007/s11222-023-10346-9)
 
  1. Bongiorno, E. G., **Chan, L.**, Goia. A. (2023). Detecting the complexitiy of a Functional time series. *Journal of Nonparametric Statistics* 
  [[Link]](https://doi.org/10.1080/10485252.2023.2234507)
  
  1. **Chan, L.**, Delsol, L., Goia, A. (2023). A link function specification test in the Single Functional Index Model. *Advances in Data Analysis and Classification* 
  [[Link]](https://doi.org/10.1007/s11634-023-00545-7)
  
  1. **Chan, L.**, Silverman, B.W., Vincent, K. (2021). Multiple Systems Estimation for sparse capture data: inferential challenges when 
  there are non-overlapping lists. *Journal of American Statistical Association* **116**(535), 1297--1306. [[Link]](https://www.tandfonline.com/doi/full/10.1080/01621459.2019.1708748)
  [[R package]](https://cran.r-project.org/web/packages/SparseMSE/index.html)
  
  1. Dryden, I., Goulding, J. Preston, S., **Chan, L.** (2020). Discussion of Multiple-systems analysis for the quantification of modern slavery: 
  classical and Bayesian approaches by Silverman. *Journal of Royal Statistical Society: Series A* **183**(3), 691--736. [[Link]](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssa.12505)
  
  1. **Chan, L.**, Grimm, U., Short, I. (2018). Substitution-based structures with absolutely continuous spectrum. *Indagationes Mathematicae* **29**(4), 1072--1086.
  [[Link]](https://www.sciencedirect.com/science/article/pii/S0019357718302659)
  
  1. **Chan, L.**, Grimm. U. (2017). Spectrum of a Rudin–Shapiro-like sequence. *Advances in Applied Mathematics* **87**, 16--23.
  [[Link]](https://www.sciencedirect.com/science/article/pii/S0196885816301397) 
  
  1. **Chan, K.**, Nair. R. (2014). Problems in Strong Uniform Distribution. *Tatra Mountains Mathematical Publications* **59**, 51--64.
  [[Link]](https://sciendo.com/article/10.2478/tmmp-2014-0018)
  
  1. **Chan, K.**, Nair. R. (2014). A remark on the distribution of Chebyshev polynomials on [−1,1]. *Uniform distribution theory* **9**(2), 125--134
  [[Link]](https://pcwww.liv.ac.uk/~karpenk/JournalUDT/vol09/no2/08ChanNair.pdf)
  
  My registered name at the University of Liverpool was Kwo Chan, short for Kwo Lik Lax Chan.
  
 

  

  
  





# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
 
